"""empty message

Revision ID: 789322dc4b67
Revises: fe57c3b26006
Create Date: 2023-02-21 17:18:38.715010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789322dc4b67'
down_revision = 'fe57c3b26006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
